(function () {
  const TOTAL_STEPS = 8;
  let current = 1;
  let firebaseConfig = null;

  // DOM refs
  const progressFill = document.getElementById('progress-fill');
  const btnPrev = document.getElementById('btn-prev');
  const btnNext = document.getElementById('btn-next');

  // --- Navigation ---

  function showStep(n) {
    document.querySelectorAll('.step').forEach((s) => s.classList.add('hidden'));
    document.getElementById('step-' + n).classList.remove('hidden');

    progressFill.style.width = ((n / TOTAL_STEPS) * 100) + '%';

    btnPrev.classList.toggle('hidden', n === 1);

    if (n === 1) btnNext.textContent = 'Get Started';
    else if (n === TOTAL_STEPS) btnNext.textContent = 'Done';
    else btnNext.textContent = 'Next';
  }

  function nextStep() {
    if (!validateStep(current)) return;
    if (current === TOTAL_STEPS) {
      // Done — go to main app
      window.location.href = 'index.html';
      return;
    }

    current++;
    if (current === 4) generateRules();
    if (current === TOTAL_STEPS) generateConfig();
    showStep(current);
  }

  function prevStep() {
    if (current > 1) {
      current--;
      showStep(current);
    }
  }

  btnNext.addEventListener('click', nextStep);
  btnPrev.addEventListener('click', prevStep);

  // --- Validation ---

  function validateStep(step) {
    if (step === 3) {
      const e1 = document.getElementById('email1').value.trim();
      const e2 = document.getElementById('email2').value.trim();
      if (!e1 || !e2) {
        alert('Please enter both email addresses.');
        return false;
      }
      if (!isEmail(e1) || !isEmail(e2)) {
        alert('Please enter valid email addresses.');
        return false;
      }
      return true;
    }
    if (step === 5) {
      const parsed = parseFirebaseConfig(document.getElementById('firebase-paste').value);
      if (!parsed) {
        alert('Could not parse Firebase config. Make sure you pasted the full firebaseConfig object.');
        return false;
      }
      firebaseConfig = parsed;
      showStatus('firebase-status', 'Config parsed successfully — project: ' + parsed.projectId, 'success');
      return true;
    }
    return true;
  }

  function isEmail(s) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
  }

  // --- Firebase config parser ---

  function parseFirebaseConfig(text) {
    if (!text.trim()) return null;
    const fields = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId'];
    const result = {};

    for (const field of fields) {
      const re = new RegExp(field + '\\s*[:=]\\s*["\']([^"\']+)["\']');
      const m = text.match(re);
      if (!m) return null;
      result[field] = m[1];
    }
    return result;
  }

  // --- Generate outputs ---

  function generateRules() {
    const e1 = document.getElementById('email1').value.trim();
    const e2 = document.getElementById('email2').value.trim();

    const rules = `rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    function isAllowedUser() {
      return request.auth != null &&
             request.auth.token.email in ['${e1}', '${e2}'];
    }

    function isOwnEntry() {
      return request.resource.data.addedBy == request.auth.uid;
    }

    match /expenses/{doc} {
      allow read: if isAllowedUser();
      allow create: if isAllowedUser() && isOwnEntry();
      allow update, delete: if isAllowedUser() && resource.data.addedBy == request.auth.uid;
    }

    match /payments/{doc} {
      allow read: if isAllowedUser();
      allow create: if isAllowedUser() && isOwnEntry();
      allow update, delete: if isAllowedUser() && resource.data.addedBy == request.auth.uid;
    }

    match /duels/{doc} {
      allow read: if isAllowedUser();
      allow create: if isAllowedUser();
      allow update: if isAllowedUser();
      allow delete: if isAllowedUser();
    }

    match /users/{userId} {
      allow read: if isAllowedUser();
      allow write: if isAllowedUser() && userId == request.auth.uid;
    }

    match /settings/{doc} {
      allow read, write: if isAllowedUser();
    }

    match /recurring/{doc} {
      allow read, write: if isAllowedUser();
    }
  }
}`;

    document.getElementById('rules-output').textContent = rules;
  }

  function generateConfig() {
    const emailjsEnabled = document.getElementById('emailjs-toggle').getAttribute('aria-pressed') === 'true';

    const config = `// Even Configuration — generated by setup wizard
const APP_CONFIG = {
  appName: "Even",

  firebase: {
    apiKey: "${firebaseConfig.apiKey}",
    authDomain: "${firebaseConfig.authDomain}",
    projectId: "${firebaseConfig.projectId}",
    storageBucket: "${firebaseConfig.storageBucket}",
    messagingSenderId: "${firebaseConfig.messagingSenderId}",
    appId: "${firebaseConfig.appId}",
  },

  emailjs: {
    enabled: ${emailjsEnabled},
    publicKey: "${emailjsEnabled ? document.getElementById('ejs-public').value.trim() : ''}",
    serviceId: "${emailjsEnabled ? document.getElementById('ejs-service').value.trim() : ''}",
    templateId: "${emailjsEnabled ? document.getElementById('ejs-template').value.trim() : ''}",
  },

  appUrl: "",
};
`;

    document.getElementById('config-output').textContent = config;
  }

  // --- EmailJS toggle ---

  document.getElementById('emailjs-toggle').addEventListener('click', function () {
    const pressed = this.getAttribute('aria-pressed') === 'true';
    this.setAttribute('aria-pressed', !pressed);
    this.textContent = pressed ? 'Off' : 'On';
    document.getElementById('emailjs-fields').classList.toggle('hidden', pressed);
  });

  // --- Copy buttons ---

  document.getElementById('btn-copy-rules').addEventListener('click', function () {
    copyToClipboard(document.getElementById('rules-output').textContent, this);
  });

  document.getElementById('btn-copy-config').addEventListener('click', function () {
    copyToClipboard(document.getElementById('config-output').textContent, this);
  });

  function copyToClipboard(text, btn) {
    navigator.clipboard.writeText(text).then(function () {
      const orig = btn.textContent;
      btn.textContent = 'Copied!';
      setTimeout(function () { btn.textContent = orig; }, 2000);
    });
  }

  // --- Download ---

  document.getElementById('btn-download').addEventListener('click', function () {
    const text = document.getElementById('config-output').textContent;
    const blob = new Blob([text], { type: 'text/javascript' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'config.js';
    a.click();
    URL.revokeObjectURL(a.href);
  });

  // --- Status helper ---

  function showStatus(id, message, type) {
    const el = document.getElementById(id);
    el.textContent = message;
    el.className = 'status status-' + type;
    el.classList.remove('hidden');
  }

  // --- Init ---
  showStep(1);
})();
